- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install required packages
  apt:
    name:
      - curl
      - python3
      - python3-pip
    state: present
  become: yes
