apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 27.3.1
    helm:
      releaseName: prometheus
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true