apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-routes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gmarinho21/Homelab'
    path: /resources/ingress-routes
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true