apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ingressroutes
  namespace: argocd
spec:
  description: 'This contains the Ingress Routes for the applications in the cluster'
  sourceRepos:
  - "*"
  destinations:
  - server: https://kubernetes.default.svc
    namespace: "argocd"
