apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gmarinho21/Homelab'
    path: resources/applications/*
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - Prune=true