apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 8.10.0
    helm:
      releaseName: grafana
      values: |
        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
            searchNamespace: ALL
          datasources:
            enabled: true
            label: grafana_datasource
            searchNamespace: ALL
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: grafana-admin-credentials
    namespace: grafana 
    jsonPointers:
    - /data