apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  source:
    chart: uptime-kuma
    repoURL: 'https://helm.irsigler.cloud'
    targetRevision: 2.21.2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kuma
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true