- name: Install K3s master
  hosts: master
  roles:
    - common
    - master

- name: Install K3s workers
  hosts: workers
  roles:
    - common
    - worker

- name: Verify cluster status
  hosts: master
  roles:
    - verify

- name: Create python venv
  hosts: master
  roles:
    - kubernetes_deps

- name: Install ArgoCD
  hosts: master
  roles:
    - argocd

- name: Bootstrap applications
  hosts: master
  roles:
    - application_setup
    - display_default_passwords
