apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.15.0
    helm:
      values: |
        config:
          clients:
            - url: http://loki-gateway.loki.svc.cluster.local:80/loki/api/v1/push
        tolerations:
          - effect: NoSchedule
            operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true