apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 5.8.9
    helm:
      values: |
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 10Gi
          affinity: {}
          tolerations: []
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
            ring:
              kvstore:
                store: inmemory
          storage:
            type: filesystem
          analytics:
            reporting_enabled: false
        monitoring:
          lokiCanary:
            enabled: false
          selfMonitoring:
            enabled: false
          serviceMonitor:
            enabled: false
        test:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true