apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
      grafana:
        port: 9099
        expose: 
          default: true
        exposedPort: 9099
        protocol: TCP